package com.peakosoft.giftlistj7.model.enums;

public enum ComplaintName {
    CRUELTY_AND_SHOCKING_CONTENT,
    MANIFESTATION_OF_HATRED,
    ILLEGAL_ACTIVITIES_OR_REGULATED_GOODS,
    SPAM,
    CALLS_FOR_VIOLENCE_OR_DANGEROUS_ACTIONS,
    PORNOGRAPHIC_SCENES,
    OTHER
}
